### PR TITLE
Add python 3.10 to test matrix

### PR DESCRIPTION
**Pull request by jairhenrique**

### CODE REVIEW

**Comment by renanivo** [comment]
Probably, most of the errors you've got are due to the deprecated versions of pytest. Now that they're gone, you can rebase with the main branch and re-run it.

**Comment by renanivo** [comment]
The problem with Flake8 should be fixed once #50 is merged

**Comment by jairhenrique** [comment]
@renanivo I forced the update from flake8 but the tests are still broken. Apparently pytest <6 doesn't work with python 3.10.

What do you think about moving this test matrix to a [tox](https://tox.wiki/en/latest/index.html) or [nox](https://nox.thea.codes/en/stable/) to get better control of the matrix?

**Comment by renanivo** [comment]
@jairhenrique Before moving to tox/nox, what about using [matrix.exclude](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-excluding-configurations-from-a-matrix) to build a matrix with compatible versions?

I think something like that should do the trick:

```yaml
   exclude:
    - python-version: "3.10"
      pytest: "pytest>=4.6.0,<5.0.0"
    - python-version: "3.10"
      pytest: "pytest>=5.0.0,<6.0.0"
```

I've never done that, but if it works, it might be easier.

**Comment by jairhenrique** [comment]
> @jairhenrique Before moving to tox/nox, what about using [matrix.exclude](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-excluding-configurations-from-a-matrix) to build a matrix with compatible versions?
> 
> I think something like this should do the trick:
> 
> ```yaml
>    exclude:
>     - python-version: "3.10"
>       pytest: "pytest>=4.6.0,<5.0.0"
>     - python-version: "3.10"
>       pytest: "pytest>=5.0.0,<6.0.0"
> ```
> 
> I've never done that, but if it works, it might be easier.

I thought it would be more complex to make this control via github actions, but it wasn't! 🚀 

All tests passed!

**Pull request merged**
