### PR TITLE
fix duplicates on skip

### PR DESCRIPTION
**Pull request by Senopiece**

### CODE REVIEW

**Comment by renanivo** [comment]
I didn't understand what's the exact use case it fixes. Can you add a description to this Pull Request and create a test for it?

**Comment by renanivo** [comment]
Oh, sorry. I have seen that you created an issue for this: #67

**Comment by Senopiece** [comment]
I reformatted the text, but I have no idea how to put it to the test, as it may actually be an issue on the eth-brownie side

**Comment by renanivo** [comment]
I'm closing this PR, as I could not find which feature is conflicting with eth-brownie. More at: #67

**Pull request closed without merging**
